# Generated by Django 2.2.4 on 2019-08-12 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='movile',
            new_name='mobile',
        ),
    ]
