# Generated by Django 2.2.4 on 2019-09-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190915_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='institutional_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', max_length=50, null=True),
        ),
    ]
