# Generated by Django 2.2.1 on 2019-07-03 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2048)),
                ('period', models.CharField(max_length=200)),
                ('direct', models.CharField(max_length=200)),
                ('student', models.CharField(max_length=200)),
                ('porcentage', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=2)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2048)),
                ('observation', models.TextField(max_length=2048)),
                ('porcentage_proposed', models.CharField(max_length=200)),
                ('porcentage_execute', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Thesis')),
            ],
        ),
    ]
