# Generated by Django 2.2.4 on 2019-09-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_civilstate_gender_healthinformation_nationality_personalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='cvlac',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cvlacStudent',
        ),
        migrations.AddField(
            model_name='student',
            name='personal_information',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='academic.PersonalInformation'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='InstitutionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvlac', models.CharField(max_length=200)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Rol')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='institutional_information',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='academic.InstitutionalInformation'),
        ),
    ]
