# Generated by Django 2.2.4 on 2019-10-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20191014_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentsthread',
            name='thesis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.Thesis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='thesis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.Thesis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentsthread',
            name='author',
            field=models.IntegerField(verbose_name='author'),
        ),
    ]
