# Generated by Django 2.2.4 on 2019-09-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20190915_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalinformation',
            name='institutional_email',
            field=models.EmailField(default='default_email@unal.edu.co', max_length=254, unique=True, verbose_name='institutional email'),
        ),
    ]
