# Generated by Django 2.2.4 on 2019-09-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_institutionalinformation_institutional_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='address',
        ),
        migrations.AddField(
            model_name='nationality',
            name='origin_country',
            field=models.CharField(default='Colombia', max_length=50),
            preserve_default=False,
        ),
    ]
