# Generated by Django 2.2.4 on 2019-10-19 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0004_auto_20191017_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Thesis')),
            ],
        ),
        migrations.DeleteModel(
            name='ComentsThread',
        ),
    ]
