# Generated by Django 2.2.4 on 2019-10-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20191019_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to='thesis_documents', verbose_name='file'),
        ),
    ]
