# Generated by Django 2.2.4 on 2019-09-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20190915_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='descripcion',
            new_name='description',
        ),
    ]
