# Generated by Django 2.2.4 on 2019-10-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20191020_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(height_field=128, null=True, upload_to='thesis_photos', width_field=128),
        ),
    ]
