# Generated by Django 2.2.4 on 2019-09-16 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_auto_20190915_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='health_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.HealthInformation'),
        ),
    ]
