# Generated by Django 2.2.4 on 2019-10-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_personalinformation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(null=True, upload_to='thesis_photos'),
        ),
    ]
