# Generated by Django 2.2.4 on 2019-10-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_auto_20191022_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='percentage',
            field=models.IntegerField(),
        ),
    ]
