# Generated by Django 2.2.4 on 2019-09-16 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_auto_20190915_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='cvlacTeacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='institutional_information',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='academic.InstitutionalInformation'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='personal_information',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='academic.PersonalInformation'),
        ),
    ]
