# Generated by Django 2.2.4 on 2019-11-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_auto_20191025_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('tremester', models.CharField(max_length=2)),
            ],
        ),
    ]
