# Generated by Django 2.2.4 on 2019-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
