# Generated by Django 2.2.4 on 2019-11-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_period_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='thesis_photos'),
        ),
    ]
