# Generated by Django 2.2.4 on 2019-09-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_auto_20190915_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
