# Generated by Django 2.2.4 on 2020-01-18 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_auto_20191109_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsthread',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='submit_date'),
            preserve_default=False,
        ),
    ]
