# Generated by Django 2.2.4 on 2019-09-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_personalinformation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
