# Generated by Django 2.2.4 on 2019-09-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_auto_20190923_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutionalinformation',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
