# Generated by Django 2.2.4 on 2019-10-02 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_auto_20190927_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to=None, verbose_name='file')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='ThesisState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
        ),
        migrations.RenameField(
            model_name='advance',
            old_name='porcentage_execute',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='advance',
            old_name='state',
            new_name='porcentage',
        ),
        migrations.RemoveField(
            model_name='advance',
            name='porcentage_proposed',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='direct',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='period',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='porcentage',
        ),
        migrations.AddField(
            model_name='thesis',
            name='co_director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_co_director', to='academic.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesis',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_director', to='academic.Teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advance',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Student'),
        ),
        migrations.CreateModel(
            name='ComentsThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='thesis',
            name='investigation_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.InvestigationLine'),
            preserve_default=False,
        ),
    ]
