# Generated by Django 2.2.4 on 2019-10-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_auto_20191001_2032'),
    ]

    def populate_investigation_line(apps, schema_editor):
        InvestigationLine = apps.get_model('academic', 'InvestigationLine')
        InvestigationLine.objects.bulk_create([
            InvestigationLine(name= "Categoría 1", description="Categoría 1"),
            InvestigationLine(name= "Categoría 2", description="Categoría 2"),
            InvestigationLine(name= "Categoría 3", description="Categoría 3"),
        ])

    operations = [
         migrations.RunPython(populate_investigation_line),
    ]
