# Generated by Django 2.2.4 on 2019-10-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_auto_20191001_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='create_date',
        ),
        migrations.AddField(
            model_name='thesis',
            name='publication_date',
            field=models.DateTimeField(default='2010-01-01', verbose_name='date publicated'),
            preserve_default=False,
        ),
    ]
