# Generated by Django 2.2.4 on 2019-10-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_auto_20191007_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance',
            old_name='porcentage',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='advance',
            name='create_date',
        ),
        migrations.AddField(
            model_name='advance',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2019-09-07', verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
