# Generated by Django 2.2.4 on 2019-10-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_auto_20191007_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThesisState',
        ),
        migrations.RemoveField(
            model_name='institutionalinformation',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
