# Generated by Django 2.2.4 on 2019-10-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_auto_20191014_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='thesis',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.ThesisState'),
        ),
    ]
