# Generated by Django 2.2.4 on 2019-10-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_auto_20191014_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='institutional_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.InstitutionalInformation'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='personal_information',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.PersonalInformation'),
        ),
    ]
