# Generated by Django 2.2.4 on 2019-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(default='2019-11-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateField(default='2019-11-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprogram',
            name='end_date',
            field=models.DateField(default='2019-11-23'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subprogram',
            name='start_date',
            field=models.DateField(default='2019-11-23'),
            preserve_default=False,
        ),
    ]
