# Generated by Django 2.2.4 on 2019-12-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20191123_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramTask',
            new_name='SubProgramTask',
        ),
        migrations.AddField(
            model_name='taskadvance',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.SubProgramTask'),
            preserve_default=False,
        ),
    ]
