# Generated by Django 2.2.4 on 2019-12-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20191201_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subprogramtask',
            old_name='comentary',
            new_name='commentary',
        ),
    ]
