# Generated by Django 2.2.4 on 2019-12-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20191201_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskadvance',
            old_name='comentary',
            new_name='commentary',
        ),
    ]
