# Generated by Django 2.2.4 on 2019-12-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20191201_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskadvance',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
