# Generated by Django 2.2.4 on 2019-12-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20191201_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskadvance',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
