# Generated by Django 2.2.4 on 2019-12-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20191201_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskadvance',
            old_name='task_file',
            new_name='advance_file',
        ),
    ]
