# Generated by Django 2.2.4 on 2019-12-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20191201_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskadvance',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
