# Generated by Django 2.2.4 on 2019-12-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_taskadvance_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
